query {
  myCompositions {
    blocks {
      ... on ContinueBlock {
        key
        lyrics
        next
        prev
        sthayi
        style
        type
      }
      ... on NoteBlock {
        key
        lyrics
        next
        prev
        shruti
        sthayi
        style
        type
      }
      ... on UndefinedBlock {
        key
        lyrics
        next
        prev
        shruti
        sthayi
        style
        type
      }
    }
    composer
    key
    raaga
    sectionTitles
    taala
    title
    useDikshitarNames
  }
}
