query ($userId: ID!, $key: ID!) {
  getComposition(belongsTo: $userId, key: $key) {
    blocks
    composer
    key
    lastUpdate
    raaga
    sectionTitles
    taala
    title
    useDikshitarNames
  }
}
