import { ChapuTaala, SuladiSaptaTaala } from '#lib/models/Taala';

export function taalaToSymbols(taala: ChapuTaala | SuladiSaptaTaala) {
  switch (taala) {
    case ChapuTaala.MisraChapu:
      return '3+4';
    case ChapuTaala.VilomaChapu:
      return '4+3';
    case ChapuTaala.KhandaChapu:
      return '2+3';
    case ChapuTaala.TisraChapu:
      return '3';
    case ChapuTaala.SankeernaChapu:
      return '4+5';
    case SuladiSaptaTaala.DhruvaTisra:
      return 'l₃Ol₃l₃';
    case SuladiSaptaTaala.DhruvaChatusra:
      return 'l₄Ol₄l₄';
    case SuladiSaptaTaala.DhruvaKhanda:
      return 'l₅Ol₅l₅';
    case SuladiSaptaTaala.DhruvaMisra:
      return 'l₇Ol₇l₇';
    case SuladiSaptaTaala.DhruvaSankeerna:
      return 'l₉Ol₉l₉';
    case SuladiSaptaTaala.MatyaTisra:
      return 'l₃Ol₃';
    case SuladiSaptaTaala.MatyaChatusra:
      return 'l₄Ol₄';
    case SuladiSaptaTaala.MatyaKhanda:
      return 'l₅Ol₅';
    case SuladiSaptaTaala.MatyaMisra:
      return 'l₇Ol₇';
    case SuladiSaptaTaala.MatyaSankeerna:
      return 'l₉Ol₉';
    case SuladiSaptaTaala.RupakaTisra:
      return 'Ol₃';
    case SuladiSaptaTaala.RupakaChatusra:
      return 'Ol₄';
    case SuladiSaptaTaala.RupakaKhanda:
      return 'Ol₅';
    case SuladiSaptaTaala.RupakaMisra:
      return 'Ol₇';
    case SuladiSaptaTaala.RupakaSankeerna:
      return 'Ol₉';
    case SuladiSaptaTaala.JhampaTisra:
      return 'l₃UO';
    case SuladiSaptaTaala.JhampaChatusra:
      return 'l₄UO';
    case SuladiSaptaTaala.JhampaKhanda:
      return 'l₅UO';
    case SuladiSaptaTaala.JhampaMisra:
      return 'l₇UO';
    case SuladiSaptaTaala.JhampaSankeerna:
      return 'l₉UO';
    case SuladiSaptaTaala.TriputaTisra:
      return 'l₃OO';
    case SuladiSaptaTaala.TriputaChatusra:
      return 'l₄OO';
    case SuladiSaptaTaala.TriputaKhanda:
      return 'l₅OO';
    case SuladiSaptaTaala.TriputaMisra:
      return 'l₇OO';
    case SuladiSaptaTaala.TriputaSankeerna:
      return 'l₉OO';
    case SuladiSaptaTaala.AtaTisra:
      return 'l₃l₃OO';
    case SuladiSaptaTaala.AtaChatusra:
      return 'l₄l₄OO';
    case SuladiSaptaTaala.AtaKhanda:
      return 'l₅l₅OO';
    case SuladiSaptaTaala.AtaMisra:
      return 'l₇l₇OO';
    case SuladiSaptaTaala.AtaSankeerna:
      return 'l₉l₉OO';
    case SuladiSaptaTaala.EkaTisra:
      return 'l₃';
    case SuladiSaptaTaala.EkaChatusra:
      return 'l₄';
    case SuladiSaptaTaala.EkaKhanda:
      return 'l₅';
    case SuladiSaptaTaala.EkaMisra:
      return 'l₇';
    case SuladiSaptaTaala.EkaSankeerna:
      return 'l₉';
  }
}
