export enum MelakartaRaaga {
  // 1. Indu Chakra
  Kanakangi = 'Kanakangi',
  Ratnangi = 'Ratnangi',
  Ganamurti = 'Ganamurti',
  Vanaspati = 'Vanaspati',
  Manavati = 'Manavati',
  Tanarupi = 'Tanarupi',

  // 2. Netra Chakra
  Senavati = 'Senavati',
  Hanumatodi = 'Hanumatodi',
  Dhenuka = 'Dhenuka',
  Natakapriya = 'Natakapriya',
  Kokilapriya = 'Kokilapriya',
  Rupavati = 'Rupavati',

  // 3. Agni Chakra
  Gayakapriya = 'Gayakapriya',
  Vakulabharanam = 'Vakulabharanam',
  Mayamalavagowla = 'Mayamalavagowla',
  Chakravakam = 'Chakravakam',
  Suryakantam = 'Suryakantam',
  Hatakambari = 'Hatakambari',

  // 4. Veda Chakra
  Jhankaradhwani = 'Jhankaradhwani',
  Natabhairavi = 'Natabhairavi',
  Keeravani = 'Keeravani',
  Kharaharapriya = 'Kharaharapriya',
  Gourimanohari = 'Gourimanohari',
  Varunapriya = 'Varunapriya',

  // 5. Bana Chakra
  Mararanjani = 'Mararanjani',
  Charukesi = 'Charukesi',
  Sarasangi = 'Sarasangi',
  Harikambhoji = 'Harikambhoji',
  Dheerasankarabaranam = 'Dheerasankarabaranam',
  Naganandini = 'Naganandini',

  // 6. Rutu Chakra
  Yagapriya = 'Yagapriya',
  Ragavardhini = 'Ragavardhini',
  Gangeyabhushani = 'Gangeyabhushani',
  Vagadheeswari = 'Vagadheeswari',
  Shulini = 'Shulini',
  Chalanata = 'Chalanata',

  // 7. Rishi Chakra
  Salagam = 'Salagam',
  Jalarnavam = 'Jalarnavam',
  Jhalavarali = 'Jhalavarali',
  Navaneetam = 'Navaneetam',
  Pavani = 'Pavani',
  Raghupriya = 'Raghupriya',

  // 8. Vasu Chakra
  Gavambhodi = 'Gavambhodi',
  Bhavapriya = 'Bhavapriya',
  Shubhapantuvarali = 'Shubhapantuvarali',
  Shadvidamargini = 'Shadvidamargini',
  Suvarnangi = 'Suvarnangi',
  Divyamani = 'Divyamani',

  // 9. Brahma Chakra
  Dhavalambari = 'Dhavalambari',
  Naamanarayani = 'Naamanarayani',
  Kamavardhini = 'Kamavardhini',
  Ramapriya = 'Ramapriya',
  Gamanashrama = 'Gamanashrama',
  Vishwambari = 'Vishwambari',

  // 10. Disi Chakra
  Shaamalangi = 'Shaamalangi',
  Shanmukhapriya = 'Shanmukhapriya',
  Simhendramadhyamam = 'Simhendramadhyamam',
  Hemavati = 'Hemavati',
  Dharmavati = 'Dharmavati',
  Neetimati = 'Neetimati',

  // 11. Rudra Chakra
  Kantamani = 'Kantamani',
  Rishabhapriya = 'Rishabhapriya',
  Latangi = 'Latangi',
  Vachaspati = 'Vachaspati',
  Mechakalyani = 'Mechakalyani',
  Chitrambari = 'Chitrambari',

  // 12. Aditya Chakra
  Sucharitra = 'Sucharitra',
  JyotiSwarupini = 'JyotiSwarupini',
  Dhatuvardani = 'Dhatuvardani',
  Naasikabhushini = 'Naasikabhushini',
  Koosalam = 'Koosalam',
  Rasikapriya = 'Rasikapriya',
}

export enum JanyaRaaga {
  // From 'Kanakangi'
  Kanakaambari = 'Kanakaambari',
  Kanakatodi = 'Kanakatodi',
  Maadhavapriyaa = 'Maadhavapriyaa',
  KarnaatakaShuddhaSaaveri = 'KarnaatakaShuddhaSaaveri',
  Latantapriya = 'Latantapriya',
  Lavangi = 'Lavangi',
  Megha = 'Megha',
  Rishabhavilaasa = 'Rishabhavilaasa',
  Sarvashree = 'Sarvashree',
  SuddhaMukhaari = 'SuddhaMukhaari',
  Tatillatika = 'Tatillatika',
  Vaageeshwari = 'Vaageeshwari',

  // From 'Rathnāngi'
  Phenadhyuti = 'Phenadhyuti',
  Ganamukhaari = 'Ganamukhaari',
  Ratnavaraali = 'Ratnavaraali',
  Revati = 'Revati',
  Shreemani = 'Shreemani',
  Shreemati = 'Shreemati',
  Svadhya = 'Svadhya',

  // From Gānamoorti
  Gaanasaamavaraali = 'Gaanasaamavaraali',
  Bhinnapanchamam = 'Bhinnapanchamam',
  Naadharanjani = 'Naadharanjani',
  Poorvavaraali = 'Poorvavaraali',
  Saamavaraali = 'Saamavaraali',

  // From Vanaspati
  Bhaanumati = 'Bhaanumati',
  Rasaali = 'Rasaali',
  Vanaavali = 'Vanaavali',
  Vittalapriya = 'Vittalapriya',

  // From Mānavati
  Manoranjani = 'Manoranjani',
  Ghanashyaamalaa = 'Ghanashyaamalaa',
  Kunjari = 'Kunjari',

  // From Tānaroopi
  Tanukeerti = 'Tanukeerti',

  // From Senāvati
  Senaagrani = 'Senaagrani',
  Bhogi = 'Bhogi',
  Chitthakarshani = 'Chitthakarshani',
  NavarasaMaalaa = 'NavarasaMaalaa',
  SindhuGowri = 'SindhuGowri',

  // From Hanumatodi
  Janatodi = 'Janatodi',
  AmritaDhanyaasi = 'AmritaDhanyaasi',
  Asaaveri = 'Asaaveri',
  Bhaanuchandrika = 'Bhaanuchandrika',
  Bhadratodi = 'Bhadratodi',
  Bhoopaalam = 'Bhoopaalam',
  Chandrikatodi = 'Chandrikatodi',
  Deshikatodi = 'Deshikatodi',
  Dhanyaasi = 'Dhanyaasi',
  Divyamaalati = 'Divyamaalati',
  Ghanta = 'Ghanta',
  Kalaasaaveri = 'Kalaasaaveri',
  Kanakasaaveri = 'Kanakasaaveri',
  Naagavaraali = 'Naagavaraali',
  Prabhupriya = 'Prabhupriya',
  Punnaagatodi = 'Punnaagatodi',
  Punnagavarali = 'Punnagavarali',
  Shravanamallika = 'Shravanamallika',
  Sowjanya = 'Sowjanya',
  ShuddhaSeemantini = 'ShuddhaSeemantini',
  ShuddhaTodi = 'ShuddhaTodi',
  Sindhubhairavi = 'Sindhubhairavi',
  Swarnamalli = 'Swarnamalli',

  // From Dhenuka
  Dhunibhinnashadjam = 'Dhunibhinnashadjam',
  Bhinnashadjam = 'Bhinnashadjam',
  Mohananaata = 'Mohananaata',
  Udayaravichandrika = 'Udayaravichandrika',
  Vasanthatodi = 'Vasanthatodi',

  // From Nātakapriya
  Nataabharanam = 'Nataabharanam',
  Alankaarapriya = 'Alankaarapriya',
  Bhaagyashabari = 'Bhaagyashabari',
  Deeparamu = 'Deeparamu',
  Gunaavati = 'Gunaavati',
  Hindoladeshikam = 'Hindoladeshikam',
  Kanakadri = 'Kanakadri',
  Maatangakaamini = 'Maatangakaamini',
  Naatyadhaarana = 'Naatyadhaarana',
  Niranjana = 'Niranjana',
  Shaanthabhaashini = 'Shaanthabhaashini',
  Shivashakti = 'Shivashakti',

  // From Kokilapriyaa
  Kokilaaravam = 'Kokilaaravam',
  Chitramani = 'Chitramani',
  Jnaanachintaamani = 'Jnaanachintaamani',
  Kowmaari = 'Kowmaari',
  ShuddhaLalitha = 'ShuddhaLalitha',
  Vardhani = 'Vardhani',
  Vasantamalli = 'Vasantamalli',
  Vasantanaaraayani = 'Vasantanaaraayani',

  // From Rupavati
  Rowpyanaka = 'Rowpyanaka',
  Shyaamakalyaani = 'Shyaamakalyaani',

  // From Gaayakapriya
  GeyaHejjajji = 'GeyaHejjajji',
  Hejjajji = 'Hejjajji',
  Kalaakaanti = 'Kalaakaanti',
  Kalkada = 'Kalkada',
  Kalpanadhaarini = 'Kalpanadhaarini',

  // From Vakulābharanam
  VaateeVasantabhairavi = 'VaateeVasantabhairavi',
  Aahiri = 'Aahiri',
  Amudhasurabhi = 'Amudhasurabhi',
  Devipriya = 'Devipriya',
  Kalindaja = 'Kalindaja',
  Kuvalayabharanam = 'Kuvalayabharanam',
  Mukthipradayini = 'Mukthipradayini',
  Sallapa = 'Sallapa',
  Soma = 'Soma',
  Suuryaa = 'Suuryaa',
  ShuddhaKaambhoji = 'ShuddhaKaambhoji',
  Vasantabhairavi = 'Vasantabhairavi',
  VasantaMukhaari = 'VasantaMukhaari',
  Vijayollaasini = 'Vijayollaasini',

  // From Māyamālava Gowla
  Ardhradesi = 'Ardhradesi',
  Bhaavini = 'Bhaavini',
  Bibhaas = 'Bibhaas',
  Bowli = 'Bowli',
  BowliRaamakriya = 'BowliRaamakriya',
  Chaaruvardhani = 'Chaaruvardhani',
  Chaayagowla = 'Chaayagowla',
  Chandrachooda = 'Chandrachooda',
  Deshyagowla = 'Deshyagowla',
  Devaranji = 'Devaranji',
  Ekakshari = 'Ekakshari',
  Ghanasindhu = 'Ghanasindhu',
  Gowla = 'Gowla',
  Gowlipantu = 'Gowlipantu',
  Gowri = 'Gowri',
  Gummakaambhoji = 'Gummakaambhoji',
  Gundakriya = 'Gundakriya',
  Gurjari = 'Gurjari',
  Jaganmohini = 'Jaganmohini',
  Kalyaanakesari = 'Kalyaanakesari',
  Kannadabangaala = 'Kannadabangaala',
  KarnaatakaSaaranga = 'KarnaatakaSaaranga',
  Lalitaa = 'Lalitaa',
  Lalitapanchamam = 'Lalitapanchamam',
  Maalavakurinji = 'Maalavakurinji',
  Maalavapanchamam = 'Maalavapanchamam',
  Maargadesi = 'Maargadesi',
  Malahari = 'Malahari',
  Mallikavasantam = 'Mallikavasantam',
  Mangalakaishiki = 'Mangalakaishiki',
  Manolayam = 'Manolayam',
  Maruva = 'Maruva',
  Mechabowli = 'Mechabowli',
  Megharanjani = 'Megharanjani',
  Nadanamakriya = 'Nadanamakriya',
  Paadi = 'Paadi',
  Pharaju = 'Pharaju',
  Poornalalita = 'Poornalalita',
  Poorvi = 'Poorvi',
  Poorvikavasanta = 'Poorvikavasanta',
  Prataapadhanyaasi = 'Prataapadhanyaasi',
  Prataaparanjani = 'Prataaparanjani',
  Puranirmai = 'Puranirmai',
  Raamakali = 'Raamakali',
  Raamakriya = 'Raamakriya',
  Revagupti = 'Revagupti',
  Rukhmaambari = 'Rukhmaambari',
  Saamantadeepara = 'Saamantadeepara',
  SaarangaNaata = 'SaarangaNaata',
  Saaveri = 'Saaveri',
  Salanganaata = 'Salanganaata',
  Satyaavati = 'Satyaavati',
  SindhuRaamakriya = 'SindhuRaamakriya',
  Surasindhu = 'Surasindhu',
  Taarakagowla = 'Taarakagowla',
  Takka = 'Takka',
  Ushaavali = 'Ushaavali',
  Vishaarada = 'Vishaarada',

  // From Chakravākam
  Toyavegavaahini = 'Toyavegavaahini',
  AahirBhairavi = 'AahirBhairavi',
  Bhakthapriya = 'Bhakthapriya',
  Bhujaangini = 'Bhujaangini',
  Bindhumaalini = 'Bindhumaalini',
  Chakranaaraayani = 'Chakranaaraayani',
  Ghoshini = 'Ghoshini',
  Guhapriya = 'Guhapriya',
  Kalaavati = 'Kalaavati',
  Kokilaa = 'Kokilaa',
  Malayamaarutam = 'Malayamaarutam',
  Mukthaangi = 'Mukthaangi',
  Mukundamaalini = 'Mukundamaalini',
  Poornapanchamam = 'Poornapanchamam',
  Pravritti = 'Pravritti',
  Raagamanjari = 'Raagamanjari',
  Rasikaranjani = 'Rasikaranjani',
  RudraPanchami = 'RudraPanchami',
  ShreeNabhomaargini = 'ShreeNabhomaargini',
  Shyaamali = 'Shyaamali',
  Subhaashini = 'Subhaashini',
  Valaji = 'Valaji',
  Veenadhaari = 'Veenadhaari',
  Vegavaahini = 'Vegavaahini',

  // From Sooryakāntam
  Chaayaavathi = 'Chaayaavathi',
  Bhairavam = 'Bhairavam',
  Haridarpa = 'Haridarpa',
  Jayasamvardhani = 'Jayasamvardhani',
  Jeevantikaa = 'Jeevantikaa',
  Kusumamaaruta = 'Kusumamaaruta',
  Naagachooḍaamani = 'Naagachooḍaamani',
  Rohini = 'Rohini',
  Saamakannada = 'Saamakannada',
  Sowraashtram = 'Sowraashtram',
  SuddhaGowla = 'SuddhaGowla',
  Supradeepam = 'Supradeepam',
  Vasanthaa = 'Vasanthaa',

  // From Hatakāmbari
  Jayashuddhamaalavi = 'Jayashuddhamaalavi',
  Hamsanantini = 'Hamsanantini',
  Kallola = 'Kallola',
  Simhala = 'Simhala',

  // From Jhankāradhvani
  Jhankaarabhramari = 'Jhankaarabhramari',
  Bhaarati = 'Bhaarati',
  Chittaranjani = 'Chittaranjani',
  Jalmika = 'Jalmika',
  Lalitabhairavi = 'Lalitabhairavi',

  // From Natabhairavi
  Naareereetigowla = 'Naareereetigowla',
  Abheri = 'Abheri',
  Anandabhairavi = 'Anandabhairavi',
  Amrithavaahini = 'Amrithavaahini',
  Bhairavi = 'Bhairavi',
  Bhuvanagaandhaari = 'Bhuvanagaandhaari',
  Chapagantarva = 'Chapagantarva',
  DarbaariKaanada = 'DarbaariKaanada',
  Devakriya = 'Devakriya',
  Dhanashree = 'Dhanashree',
  Dharmaprakaashini = 'Dharmaprakaashini',
  DilipikaVasantha = 'DilipikaVasantha',
  Divyagaandhaari = 'Divyagaandhaari',
  Gopikaavasantam = 'Gopikaavasantam',
  Hindolam = 'Hindolam',
  Hindolavasanta = 'Hindolavasanta',
  Indughantarava = 'Indughantarava',
  Jayanthashrii = 'Jayanthashrii',
  Jingala = 'Jingala',
  Jonpuri = 'Jonpuri',
  Kaatyaayani = 'Kaatyaayani',
  Kanakavasantham = 'Kanakavasantham',
  Kshanika = 'Kshanika',
  Maanji = 'Maanji',
  Mahati = 'Mahati',
  Malkosh = 'Malkosh',
  Maargahindoolam = 'Maargahindoolam',
  Naagagaandhaari = 'Naagagaandhaari',
  NavarathnaVilaasam = 'NavarathnaVilaasam',
  Niilamati = 'Niilamati',
  Niilaveni = 'Niilaveni',
  Poornashadjam = 'Poornashadjam',
  Raajaraajeshwari = 'Raajaraajeshwari',
  Saaramati = 'Saaramati',
  SaarangaKaapi = 'SaarangaKaapi',
  Sharadapriya = 'Sharadapriya',
  ShreeNavarasachandrika = 'ShreeNavarasachandrika',
  SindhuDhanyaasi = 'SindhuDhanyaasi',
  ShuddhaDesi = 'ShuddhaDesi',
  ShuddhaSaalavi = 'ShuddhaSaalavi',
  Sukumaari = 'Sukumaari',
  Sushama = 'Sushama',
  Sutradhaari = 'Sutradhaari',
  Tarkshika = 'Tarkshika',
  Udayaraaga = 'Udayaraaga',
  Vasantavaraali = 'Vasantavaraali',
}
