mutation ($composition: CompositionInput!) {
  saveComposition(composition: $composition) {
    blocks
    composer
    key
    lastUpdate
    raaga
    sectionTitles
    taala
    title
    useDikshitarNames
  }
}
