export enum SuladiSaptaTaala {
  DhruvaTisra = 'DhruvaTisra',
  DhruvaChatusra = 'DhruvaChatusra',
  DhruvaKhanda = 'DhruvaKhanda',
  DhruvaMisra = 'DhruvaMisra',
  DhruvaSankeerna = 'DhruvaSankeerna',
  MatyaTisra = 'MatyaTisra',
  MatyaChatusra = 'MatyaChatusra',
  MatyaKhanda = 'MatyaKhanda',
  MatyaMisra = 'MatyaMisra',
  MatyaSankeerna = 'MatyaSankeerna',
  RupakaTisra = 'RupakaTisra',
  RupakaChatusra = 'RupakaChatusra',
  RupakaKhanda = 'RupakaKhanda',
  RupakaMisra = 'RupakaMisra',
  RupakaSankeerna = 'RupakaSankeerna',
  JhampaTisra = 'JhampaTisra',
  JhampaChatusra = 'JhampaChatusra',
  JhampaKhanda = 'JhampaKhanda',
  JhampaMisra = 'JhampaMisra',
  JhampaSankeerna = 'JhampaSankeerna',
  TriputaTisra = 'TriputaTisra',
  TriputaChatusra = 'TriputaChatusra',
  TriputaKhanda = 'TriputaKhanda',
  TriputaMisra = 'TriputaMisra',
  TriputaSankeerna = 'TriputaSankeerna',
  AtaTisra = 'AtaTisra',
  AtaChatusra = 'AtaChatusra',
  AtaKhanda = 'AtaKhanda',
  AtaMisra = 'AtaMisra',
  AtaSankeerna = 'AtaSankeerna',
  EkaTisra = 'EkaTisra',
  EkaChatusra = 'EkaChatusra',
  EkaKhanda = 'EkaKhanda',
  EkaMisra = 'EkaMisra',
  EkaSankeerna = 'EkaSankeerna',
}

export enum ChapuTaala {
  MisraChapu = 'MisraChapu',
  VilomaChapu = 'VilomaChapu',
  KhandaChapu = 'KhandaChapu',
  TisraChapu = 'TisraChapu',
  SankeernaChapu = 'SankeernaChapu',
}
